name: live_notes
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.7.4
  firebase_auth: ^0.5.19
  shared_preferences: ^0.4.2
  intl: ^0.15.7
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/live_notes_logo.png
    - assets/logo.png
    - assets/landing.jpeg
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700